// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slleauhyjnmiawosvlcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsbGVhdWh5am5taWF3b3N2bGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NTYxMzcsImV4cCI6MjA3NTMzMjEzN30.mcRvjoJbmQG2s5UBsfczYA8tryuQRmxiW1RZOi4vLFk"
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});