// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwpaukpireqzghidirsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cGF1a3BpcmVxemdoaWRpcnNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjg2MDAsImV4cCI6MjA3NDY0NDYwMH0.ZML7ChKNXR-uC-9w0CNV_UzvmqbO5jqh8U2W3M9Ld8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});