import feedparser

# Flux RSS BOFiP (max résultats, 60 jours)
url_rss = "https://bofip.impots.gouv.fr/bofip/ext/rss.xml?actualites=1&publications=1&series=IR-CHAMP:IR-BASE:IR-LIQ:IR-RICI:IR-DECLA:IR-PAS:IR-PAIE:IR-PROCD:IR-CESS:IR-DOMIC:IR-CHR:RSA-CHAMP:RSA-GEO:RSA-BASE:RSA-PENS:RSA-ES:RSA-GER:RPPM-PVBMC:RPPM-RCM:RPPM-PVBMI:RFPI-CHAMP:RFPI-BASE:RFPI-DECLA:RFPI-SPEC:RFPI-PROCD:RFPI-CTRL:RFPI-PVI:RFPI-PVINR:RFPI-SPI:RFPI-TDC:RFPI-TPVIE:BA-CHAMP:BA-REG:BA-BASE:BA-LIQ:BA-RICI:BA-DECLA:BA-PROCD:BA-SECT:BA-CESS:BNC-CHAMP:BNC-BASE:BNC-RICI:BNC-DECLA:BNC-PROCD:BNC-SECT:BNC-CESS:BIC-CHAMP:BIC-BASE:BIC-PDSTK:BIC-CHG:BIC-PVMV:BIC-AMT:BIC-PROV:BIC-DEF:BIC-RICI:BIC-DECLA:BIC-PROCD:BIC-CESS:BIC-PTP:IS-CHAMP:IS-BASE:IS-DEF:IS-LIQ:IS-RICI:IS-DECLA:IS-AUT:IS-PROCD:IS-GEO:IS-CESS:IS-FUS:IS-GPE:TVA-CHAMP:TVA-BASE:TVA-LIQ:TVA-DED:TVA-DECLA:TVA-PROCD:TVA-GEO:TVA-SECT:TVA-IMM:TVA-AU:TCA-TSN:TCA-OCE:TCA-CDP:TCA-CAEA:TCA-RSAB:TCA-RSD:TCA-PPA:TCA-TPA:TCA-CSR:TCA-AHJ:TCA-RSP:TCA-PJP:TCA-PJC:TCA-TPC:TCA-BNA:TCA-AUTO:TCA-RPE:TCA-FIN:TCA-POLL:TCA-TRC:CVAE-CHAMP:CVAE-BASE:CVAE-LIQ:CVAE-LIEU:CVAE-DECLA:CVAE-PROCD:TPS-TS:TPS-PEEC:TPS-EMOE:TPS-THR:TFP-CAP:TFP-IFER:TFP-MINES:TFP-GUF:TFP-PYL:TFP-TEM:TFP-TSC:TFP-TASC:TFP-ASSUR:TFP-TFSCT:TFP-TEH:AIS-MOB:AIS-CCN:IF-COLOC:IF-TFNB:IF-TFB:IF-TH:IF-CFE:IF-AUT:PAT-IFI:PAT-ISF:PAT-TPC:PAT-CAP:ENR-DG:ENR-DMTOI:ENR-DMTOM:ENR-JOMI:ENR-DMTG:ENR-PTG:ENR-AVS:ENR-TIM:TCAS-ASSUR:TCAS-AUT:REC-PART:REC-PRO:REC-PREA:REC-GAR:REC-FORCE:REC-SOLID:REC-EVTS:DAE-10:DAE-20:CF-DG:CF-CPF:CF-COM:CF-IOR:CF-PGR:CF-CMSS:CF-INF:CTX-DG:CTX-PREA:CTX-ADM:CTX-JUD:CTX-DRO:CTX-REP:CTX-RDI:CTX-GCX:CTX-DRS:CTX-BF:SJ-AGR:SJ-RES:INT-DG:INT-AEA:INT-CVB:CAD-TOPO:CAD-REM:CAD-AFR:CAD-MAJ:CAD-INFO:CAD-DIFF:DJC-COVID19:DJC-CADA:DJC-FIN:DJC-OA:DJC-EXPC:DJC-TDC:DJC-TRUST:DJC-SECR:DJC-ARF:DJC-DES:BAREME-000000:FORM-000000:LETTRE-000000:CARTE-000000:ANNX-000000&maxR=sans&maxJ=60"
feed = feedparser.parse(url_rss)

# Variable pour savoir si on a trouvé le BOI recherché
boi_detecte = False

for entry in feed.entries:
    titre = entry.title
    lien = entry.link
    description = entry.description

    print(f"Titre      : {titre}")
    print(f"Lien       : {lien}")
    print(f"Description: {description}\n")

    # Vérification
    if "BOI-BAREME-000001" in titre or "BOI-BAREME-000001" in description:
        boi_detecte = True

# Résultat final
print("="*80)
if boi_detecte:
    print("✅ BOI-BAREME-000037 détecté dans l'actualité.")
else:
    print("❌ BOI-BAREME-000037 non détecté dans l'actualité.")